activity_frequency: hourly
amygdala_stress_weight: 0.6
debug_mode: false
display_width: 80
enable_random_events: true
forgetting_rate: 0.01
initial_bond: 30
initial_energy: 70
initial_happiness: 85
initial_health: 95
initial_hunger: 40
initial_trust: 50
max_working_memory: 10
memory_retrieval_count: 5
memory_significance_threshold: 6.0
nanogpt_api_key: '1628569b-b23b-42f4-ade5-b32a658d5c4a'
nanogpt_endpoint: https://nano-gpt.com/api/v1/chat/completions
nanogpt_max_tokens: 150
nanogpt_model: chatgpt-4o-latest
nanogpt_temperature: 0.8
personality_bravery: 5
personality_curiosity: 8
personality_independence: 6
personality_loyalty: 10
personality_playfulness: 9
show_brain_council: false
show_memory_retrieval: false
show_stats_bar: true
significant_event_chance: 0.15
starting_location: trainer_home
time_acceleration: 1.0
use_color: true
verbose_logging: true
vote_weight_amygdala: 0.3
vote_weight_cerebellum: 0.1
vote_weight_hippocampus: 0.2
vote_weight_hypothalamus: 0.15
vote_weight_prefrontal: 0.25
weather_change_frequency: daily
